"""Alterando nome da tabela

Revision ID: 98232d7bf68a
Revises: 336e804cc72a
Create Date: 2026-06-01 19:11:35.463575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '98232d7bf68a'
down_revision: Union[str, Sequence[str], None] = '336e804cc72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    op.drop_column('transactions', 'trasaction_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('trasaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
